name: CI/CD MonBlog

on:
  push:
    branches: ["main"]

jobs:
  # =========================
  # JOB 1 : CI (Build & Push)
  # =========================
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le code du repo
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2) Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Construire et pousser l’image vers Docker Hub
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/monblog-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/monblog-web:${{ github.sha }}

  # =========================
  # JOB 2 : CD (Deploy serveur)
  # =========================
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      # 1) Se connecter au serveur en SSH et déployer
      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/monblog-prod

            # Pull la dernière image web
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/monblog-web:latest

            # Redémarrer les services
            docker compose -f docker-compose.prod.yml up -d

            # Nettoyage optionnel des anciennes images inutilisées
            docker image prune -f
